#!/usr/bin/env bash
# Displays line indefinety and prints message upon reciving a sigkill message


function handle_sigTerm {
        echo "I am invincible!!"
}

while true
do
        echo "To infinity and beyond"
	trap handle_sigTerm SIGTERM
        sleep 2
done
