#!/usr/bin/env bash
# Displays line indefinety and prints message upon reciving a sigkill 

trap "echo 'I am invincible!!!'" 15

while true
do
        echo "To infinity and beyond"
        sleep 2
done
